---
settings:
  name: NetApp solutions for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Soluções para SAP
    url: "/index.html"
  - title: O que há de novo
    url: "/whats-new.html"
  - section: bp
  - section: backup
  - section: lifecycle
  - section: briefs
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: NetApp solutions
  repo: netapp-solutions-family
