---
sidebar: sidebar 
permalink: backup/fsxn-overview.html 
keywords: tr4926, 4926, introduction, overview 
summary: Este relatório técnico fornece as práticas recomendadas para proteção de dados SAP HANA no Amazon FSX for NetApp ONTAP e NetApp SnapCenter. Este documento abrange os conceitos do SnapCenter, as recomendações de configuração e os fluxos de trabalho operacionais, incluindo configurações, operações de backup e operações de restauração e recuperação. 
---
= TR-4926: SAP HANA no Amazon FSX for NetApp ONTAP - Backup e recuperação com o SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este relatório técnico fornece as práticas recomendadas para proteção de dados SAP HANA no Amazon FSX for NetApp ONTAP e NetApp SnapCenter. Este documento abrange os conceitos do SnapCenter, as recomendações de configuração e os fluxos de trabalho operacionais, incluindo configurações, operações de backup e operações de restauração e recuperação.

Autor: Nils Bauer, NetApp

Hoje, as empresas exigem disponibilidade contínua e ininterrupta para suas aplicações SAP. Elas esperam níveis de performance consistentes diante de volumes cada vez maiores de dados e da necessidade de tarefas de manutenção de rotina, como backups do sistema. Realizar backups de bancos de dados SAP é uma tarefa essencial e pode ter um impacto significativo no desempenho do sistema SAP de produção.

As janelas de backup estão encolhendo enquanto a quantidade de dados a serem copiados está aumentando. Portanto, é difícil encontrar um momento em que você pode executar backups com efeito mínimo nos processos de negócios. O tempo necessário para restaurar e recuperar os sistemas SAP é uma preocupação porque o tempo de inatividade para sistemas de produção e não produção SAP deve ser minimizado para reduzir os custos para os negócios.
