---
sidebar: sidebar 
permalink: backup/fsxn-additional-info.html 
keywords:  
summary:  
---
= Onde encontrar informações adicionais
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para saber mais sobre as informações descritas neste documento, consulte os seguintes documentos e/ou sites:

* Guia do usuário do FSX for NetApp ONTAP: O que é o Amazon FSX para NetApp ONTAP?
+
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html[]

* Página de recursos do SnapCenter
+
https://www.netapp.com/us/documentation/snapcenter-software.aspx["https://www.netapp.com/us/documentation/snapcenter-software.aspx"]

* Documentação do software SnapCenter
+
https://docs.netapp.com/us-en/snapcenter/index.html["https://docs.netapp.com/us-en/snapcenter/index.html"]

* TR-4667: Automatizando as operações de clonagem e cópia do sistema SAP HANA com o SnapCenter
+
link:../lifecycle/sc-copy-clone-introduction.html["Automatizando as operações de clonagem e cópia do sistema SAP HANA com o SnapCenter"]

* TR-4719: Replicação do sistema SAP HANA: Backup e recuperação com o SnapCenter
+
link:hana-sr-scs-system-replication-overview.html["Backup e recuperação com o SnapCenter"]





== Histórico de versões

|===
| Versão | Data | Histórico de versões do documento 


| Versão 1,0 | Maio de 2022 | Lançamento inicial. 
|===