---
sidebar: sidebar 
permalink: backup/hana-hycl-backup-info-version.html 
keywords: BlueXP, SAP HANA, restore 
summary: Esta seção lista onde encontrar informações adicionais e mostra o histórico de versões. 
---
= Informações adicionais e Histórico de versões
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta seção lista onde encontrar informações adicionais e mostra o histórico de versões.



== Onde encontrar informações adicionais

Para saber mais sobre as informações descritas neste documento, consulte os seguintes documentos e/ou sites:

* Documentação do produto de backup e recuperação do NetApp BlueXP  https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protect-app-data-to-cloud.html["Proteja seus dados de aplicativos locais | Documentação da NetApp"]
* link:hana-br-scs-overview.html#the-netapp-solution["Backup e recuperação do SAP HANA com o SnapCenter"]




== Histórico de versões

[cols="17%,23%,60%"]
|===
| Versão | Data | Histórico de versões do documento 


| Versão 1,0 | Março de 2024 | Versão inicial 
|===
Consulte o http://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade (IMT)"] no site de suporte da NetApp para validar se as versões exatas de produtos e recursos descritas neste documento são compatíveis com o seu ambiente específico. O NetApp IMT define os componentes e versões do produto que podem ser usados para construir configurações compatíveis com o NetApp. Os resultados específicos dependem da instalação de cada cliente de acordo com as especificações publicadas.
