---
sidebar: sidebar 
permalink: backup/saphana-dr-anf_requirements_and_best_practices.html 
keywords: requirements, best, practices, microsoft, azure, virtual, machine, vm 
summary: 'O Microsoft Azure não garante a disponibilidade de um tipo de máquina virtual (VM) específico na criação ou ao iniciar uma VM desalocada.' 
---
= Requisitos e práticas recomendadas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O Microsoft Azure não garante a disponibilidade de um tipo de máquina virtual (VM) específico na criação ou ao iniciar uma VM desalocada. Especificamente, em caso de falha de região, muitos clientes podem exigir VMs adicionais na região de recuperação de desastres. Portanto, é recomendável usar ativamente uma VM com o tamanho necessário para o failover de desastres como um sistema de teste ou QA na região de recuperação de desastres para ter o tipo de VM necessário alocado.

Para otimização dos custos, faz sentido usar um pool de capacidade do ANF com uma categoria de performance mais baixa durante as operações normais. A replicação de dados não exige alta performance e, portanto, pode usar um pool de capacidade com uma categoria de performance padrão. Para testes de recuperação de desastre ou se for necessário um failover de desastre, os volumes precisam ser movidos para um pool de capacidade com uma categoria de alta performance.

Se um segundo pool de capacidade não for uma opção, os volumes de destino de replicação devem ser configurados com base nos requisitos de capacidade e não nos requisitos de desempenho durante as operações normais. A cota ou a taxa de transferência (para QoS manual) pode ser adaptada para testes de recuperação de desastres em caso de failover de desastres.

Mais informações podem ser encontradas em https://docs.microsoft.com/en-us/azure/azure-netapp-files/cross-region-replication-requirements-considerations["Requisitos e considerações para usar a replicação entre regiões de volume Azure NetApp Files | Microsoft Docs"^].
