---
sidebar: sidebar 
permalink: backup/saphana-backup-anf-overview.html 
keywords: overview, introduction, tr-4905, 4905, tr4905, snapcenter service, anf, azure netapp files 
summary: Este relatório técnico abrange as práticas recomendadas para proteção de dados do SAP HANA com o Serviço NetApp SnapCenter e o Azure NetApp Files. Ele abrange os conceitos do Serviço SnapCenter, recomendações de configuração e workflows operacionais, incluindo operações de backup e restauração e recuperação. 
---
= TR-4905: Backup e recuperação do SAP HANA no Azure NetApp Files com o Serviço SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este relatório técnico abrange as práticas recomendadas para proteção de dados do SAP HANA com o Serviço NetApp SnapCenter e o Azure NetApp Files. Ele abrange os conceitos do Serviço SnapCenter, recomendações de configuração e workflows operacionais, incluindo operações de backup e restauração e recuperação.

Autor: Nils Bauer, NetApp

Hoje, as empresas exigem disponibilidade contínua e ininterrupta para suas aplicações SAP. Elas esperam níveis de performance consistentes diante de volumes cada vez maiores de dados e da necessidade de tarefas de manutenção de rotina, como backups do sistema. Realizar backups de bancos de dados SAP é uma tarefa crítica e pode ter um efeito significativo no desempenho do sistema SAP de produção.

As janelas de backup estão encolhendo, enquanto a quantidade de dados a serem copiados está aumentando. Portanto, é difícil encontrar um momento em que os backups podem ser realizados com o mínimo efeito nos processos de negócios. O tempo necessário para restaurar e recuperar os sistemas SAP é uma preocupação, porque o tempo de inatividade para sistemas de produção e não produção SAP precisa ser minimizado para reduzir a perda de dados e o custo para os negócios.

Os pontos a seguir resumem os desafios enfrentados pelo backup e recuperação SAP:

* * Efeitos de desempenho em sistemas SAP de produção.* Normalmente, os backups tradicionais baseados em cópia criam um consumo significativo de desempenho em sistemas SAP de produção devido às cargas pesadas colocadas no servidor de banco de dados, no sistema de storage e na rede de storage.
* * Janelas de backup encolhidas.* Os backups convencionais só podem ser feitos quando poucas atividades de diálogo ou lote estão em andamento no sistema SAP. O agendamento de backups torna-se mais difícil quando os sistemas SAP estão em uso 24 horas por dia.
* *Rápido crescimento de dados.* O rápido crescimento de dados e a diminuição dos períodos de backup exigem um investimento contínuo na infraestrutura de backup. Em outras palavras, você deve adquirir espaço em disco de backup adicional e redes de backup mais rápidas. Você também precisa cobrir as despesas contínuas de armazenamento e gerenciamento desses ativos de backup. Backups incrementais ou diferenciais podem resolver esses problemas, mas esse arranjo resulta em um processo de restauração muito lento, complicado e complexo que é mais difícil de verificar. Esses sistemas geralmente aumentam os tempos de objetivo de tempo de recuperação (rto) e objetivo do ponto de restauração (RPO) de maneiras que não são aceitáveis para os negócios.
* *Aumento do custo do tempo de inatividade.* O tempo de inatividade não planejado de um sistema SAP geralmente afeta as finanças da empresa. Uma parte significativa de qualquer tempo de inatividade não planejado é consumida pelo requisito de restaurar e recuperar o sistema SAP. Portanto, o rto desejado dita o design da arquitetura de backup e recuperação.
* *Tempo de backup e recuperação para projetos de atualização SAP.* O plano de projeto para uma atualização SAP inclui pelo menos três backups do banco de dados SAP. Esses backups reduzem significativamente o tempo disponível para o processo de atualização. A decisão de prosseguir é geralmente baseada no tempo necessário para restaurar e recuperar o banco de dados do backup criado anteriormente. Em vez de apenas restaurar um sistema para o seu estado anterior, uma restauração rápida fornece mais tempo para resolver problemas que podem ocorrer durante uma atualização.

