---
sidebar: sidebar 
permalink: bp/hana-asa-fc-io-stack-configuration.html 
keywords: io, i/o, stack, configuration, database 
summary: A partir do SAP HANA 1,0 SPS10, a SAP introduziu parâmetros para ajustar o comportamento de e/S e otimizar o banco de dados para o sistema de arquivos e storage usado. 
---
= Configuração de pilha de e/S para SAP HANA
:allow-uri-read: 




== Configuração de pilha de e/S para SAP HANA

A partir do SAP HANA 1,0 SPS10, a SAP introduziu parâmetros para ajustar o comportamento de e/S e otimizar o banco de dados para o sistema de arquivos e storage usado.

A NetApp realizou testes de desempenho para definir os valores ideais. A tabela a seguir lista os valores ideais como inferidos dos testes de desempenho.

|===
| Parâmetro | Valor 


| max_parallel_io_requests | 128 


| async_read_submit | ligado 


| async_write_submit_active | ligado 


| async_write_submit_blocks | tudo 
|===
Para SAP HANA 1,0 até SPS12HANA, esses parâmetros podem ser definidos durante a instalação do banco de dados SAP HANA, conforme descrito na SAP https://launchpad.support.sap.com/["2267798 – Configuração do banco de dados SAP HANA durante a instalação usando hdbparam"^] Note .

Como alternativa, os parâmetros podem ser definidos após a instalação do banco de dados SAP HANA usando a `hdbparam` estrutura.

....
FC5adm@sapcc-hana-tst:/usr/sap/FC5/HDB00> hdbparam --paramset fileio.max_parallel_io_requests=128
FC5adm@sapcc-hana-tst:/usr/sap/FC5/HDB00> hdbparam --paramset fileio.async_write_submit_active=on
FC5adm@sapcc-hana-tst:/usr/sap/FC5/HDB00> hdbparam --paramset fileio.async_read_submit=on
FC5adm@sapcc-hana-tst:/usr/sap/FC5/HDB00> hdbparam --paramset fileio.async_write_submit_blocks=all
....
A partir do SAP HANA 2,0, `hdbparam` está obsoleto e os parâmetros são movidos para o `global.ini` arquivo. Os parâmetros podem ser definidos usando comandos SQL ou SAP HANA Studio. Para obter mais detalhes, consulte a nota SAP https://launchpad.support.sap.com/["2399079: Eliminação do hdbparam em HANA 2"^] . Os parâmetros também podem ser definidos dentro do `global.ini` arquivo.

....
FC5adm@sapcc-hana-tst: /usr/sap/FC5/SYS/global/hdb/custom/config> cat global.ini
…
[fileio]
async_read_submit = on
async_write_submit_active = on
max_parallel_io_requests = 128
async_write_submit_blocks = all
…
....
Para SAP HANA 2,0 SPS5 e posterior, use o `setParameter.py` script para definir os parâmetros corretos.

....
fc5adm@sapcc-hana-tst-03:/usr/sap/FC5/HDB00/exe/python_support>
python setParameter.py -set=SYSTEM/global.ini/fileio/max_parallel_io_requests=128
python setParameter.py -set=SYSTEM/global.ini/fileio/async_read_submit=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_active=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_blocks=all
....