---
sidebar: sidebar 
permalink: bp/hana-asa-fc-host-setup_multi.html 
keywords: multipathing, fcp, hba, configure 
summary: Antes de configurar o host, os utilitários de host SAN NetApp devem ser baixados do site de suporte da NetApp e instalados nos servidores HANA. A documentação do utilitário host inclui informações sobre software adicional que deve ser instalado dependendo do HBA FCP usado. 
---
= Configuração de múltiplos hosts
:allow-uri-read: 




== Configuração de múltiplos hosts

[role="lead"]
Este capítulo descreve a configuração de um sistema de múltiplos hosts SAP HANA 2+1 como exemplo.



== Configuração de LUN para sistemas SAP HANA de múltiplos hosts

O Linux LVM está sendo usado para aumentar o desempenho e abordar limitações de tamanho de LUN.

No host SAP HANA, grupos de volume e volumes lógicos precisam ser criados e montados, como indicado na tabela a seguir.

|===
| Volume lógico (VL) | Ponto de montagem no host SAP HANA | Nota 


| LV: FC5_data_mnt00001-vol | /Hana/data/FC5/mnt00001 | Montado usando o conetor de armazenamento 


| LV: FC5_log_mnt00001-vol | /Hana/log/FC5/mnt00001 | Montado usando o conetor de armazenamento 


| LV: FC5_data_mnt00002-vol | /Hana/data/FC5/mnt00002 | Montado usando o conetor de armazenamento 


| LV: FC5_log_mnt00002-vol | /Hana/log/FC5/mnt00002 | Montado usando o conetor de armazenamento 


| Compartilhamento NFS externo: FC5_shared | /hana/compartilhado | Montado em todos os hosts usando entrada NFS e /etc/fstab 
|===

NOTE: Os sistemas SAP HANA de múltiplos hosts exigem  `/hana/shared` Sistema de arquivos conectado a todos os hosts de um sistema. Normalmente, trata-se de um compartilhamento NFS fornecido por um servidor NFS. Recomenda-se usar um servidor NFS de alta disponibilidade, como um sistema NetApp FAS ou AFF. Outra opção é usar o servidor NFS integrado de um host Linux para isso.


NOTE: Com a configuração descrita, o  `/usr/sap/FC5` O diretório no qual o diretório inicial padrão do usuário FC5adm está armazenado está no disco local de cada host HANA. Em uma configuração de recuperação de desastres com replicação baseada em disco, a NetApp recomenda o uso de quatro LUNs adicionais para  `/usr/sap/FC5` sistema de arquivos de cada host para que cada host de banco de dados tenha todos os seus sistemas de arquivos no armazenamento central.



=== Crie grupos de volumes LVM e volumes lógicos

. Inicialize todos os LUNs como um volume físico.
+
....
pvcreate /dev/mapper/svm1-FC5_data_mnt00001_1
pvcreate /dev/mapper/svm1-FC5_data_mnt00001_2
pvcreate /dev/mapper/svm1-FC5_data_mnt00002_1
pvcreate /dev/mapper/svm1-FC5_data_mnt00002_2
pvcreate /dev/mapper/svm1-FC5_log_mnt00001_1
pvcreate /dev/mapper/svm1-FC5_log_mnt00001_2
pvcreate /dev/mapper/svm1-FC5_log_mnt00002_1
pvcreate /dev/mapper/svm1-FC5_log_mnt00002_2
....
. Crie os grupos de volume para cada partição de dados e log.
+
....
vgcreate FC5_data_mnt00001 /dev/mapper/svm1-FC5_data_mnt00001_1 /dev/mapper/svm1-FC5_data_mnt00001_2
vgcreate FC5_data_mnt00002 /dev/mapper/svm1-FC5_data_mnt00002_1 /dev/mapper/svm1-FC5_data_mnt00002_2
vgcreate FC5_log_mnt00001 /dev/mapper/svm1-FC5_log_mnt00001_1 /dev/mapper/svm1-FC5_log_mnt00001_2
vgcreate FC5_log_mnt00002 /dev/mapper/svm1-FC5_log_mnt00002_1 /dev/mapper/svm1-FC5_log_mnt00002_2
....
. Crie um volume lógico para cada partição de dados e log. Use um tamanho de faixa que seja igual ao número de LUNs usados por grupo de volume (neste exemplo, é dois) e um tamanho de faixa de 256K para dados e 64k para log. O SAP suporta apenas um volume lógico por grupo de volumes.
+
....
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00001
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00002
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00002
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00001
....
. Examine os volumes físicos, os grupos de volume e os grupos de vol em todos os outros hosts.


....
modprobe dm_mod
pvscan
vgscan
lvscan
....

NOTE: Se esses comandos não localizarem os volumes, será necessário reiniciar.

Para montar os volumes lógicos, os volumes lógicos devem ser ativados. Para ativar os volumes, execute o seguinte comando:

....
vgchange -a y
....


=== Criar sistemas de arquivos

Crie o sistema de arquivos XFS em todos os dados e volumes lógicos de log.

....
mkfs.xfs /dev/mapper/FC5_data_mnt00001-vol
mkfs.xfs /dev/mapper/FC5_data_mnt00002-vol
mkfs.xfs /dev/mapper/FC5_log_mnt00001-vol
mkfs.xfs /dev/mapper/FC5_log_mnt00002-vol
....


=== Crie pontos de montagem

Crie os diretórios de ponto de montagem necessários e defina as permissões em todos os hosts de trabalho e de espera:

....
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00002
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00002
sapcc-hana-tst:/ # mkdir -p /hana/shared
sapcc-hana-tst:/ # chmod -R 777 /hana/log/FC5
sapcc-hana-tst:/ # chmod -R 777 /hana/data/FC5
sapcc-hana-tst:/ # chmod 777 /hana/shared
....


=== Montar sistemas de arquivos

Para montar o  `/hana/shared` sistemas de arquivos durante a inicialização do sistema usando o  `/etc/fstab` arquivo de configuração, adicione o  `/hana/shared` sistema de arquivos para o  `/etc/fstab` arquivo de configuração de cada host.

....
sapcc-hana-tst:/ # cat /etc/fstab
<storage-ip>:/hana_shared /hana/shared nfs rw,vers=3,hard,timeo=600, intr,noatime,nolock 0 0
....

NOTE: Todos os sistemas de arquivos de log e dados são montados pelo conector de storage SAP HANA.

Para montar os sistemas de arquivos, execute o `mount -a` comando em cada host.
