---
sidebar: sidebar 
permalink: bp/hana-fas-fc-host-setup.html 
keywords: configure, multipathing, create, lvm, volume, groups, logical, mount, points, file, systems 
summary: A documentação também contém informações sobre configurações multipath específicas à versão Linux usada. 
---
= Configuração do host
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de configurar o host, os Utilitários de host SAN NetApp devem ser baixados do http://mysupport.netapp.com/["Suporte à NetApp"^] site e instalados nos servidores HANA. A documentação do Utilitário de host inclui informações sobre software adicional que deve ser instalado dependendo do HBA FCP usado.

A documentação também contém informações sobre configurações multipath específicas à versão Linux usada. Este documento aborda as etapas de configuração necessárias para o SLES 15 e Red Hat Enterprise Linux 7,6 ou posterior, conforme descrito no https://library.netapp.com/ecm/ecm_download_file/ECMLP2547958["Linux Host Utilities 7,1 Guia de instalação e configuração"^].



== Configurar multipathing


NOTE: As etapas de 1 a 6 devem ser executadas em todos os hosts de trabalho e de espera na configuração de vários hosts do SAP HANA.

Para configurar multipathing, execute as seguintes etapas:

. Execute o comando Linux `rescan-scsi-bus.sh -a` em cada servidor para descobrir novos LUNs.
. Execute o `sanlun lun show` comando e verifique se todos os LUNs necessários estão visíveis. O exemplo a seguir mostra a `sanlun lun show` saída de comando para um 2 sistema HANA de mais de 1 host com dois LUNs de dados e dois LUNs de log. A saída mostra os LUNs e os arquivos de dispositivo correspondentes, como LUN `SS3_data_mnt00001` e o arquivo de dispositivo `/dev/sdag` . Cada LUN tem oito caminhos de FC do host para as controladoras de storage.
+
....
stlrx300s8-6:~ # sanlun lun show
controller(7mode/E-Series)/                                            device          host       lun
vserver(cDOT/FlashRay)        lun-pathname                             filename        adapter    protocol   size    product
-------------------------------------------------------------------------------------------------------------------------
hana                          /vol/SS3_log_mnt00002/SS3_log_mnt00002   /dev/sdah       host11     FCP        512.0g  cDOT
hana                          /vol/SS3_data_mnt00001/SS3_data_mnt00001 /dev/sdag       host11     FCP        1.2t    cDOT
hana                          /vol/SS3_data_mnt00002/SS3_data_mnt00002 /dev/sdaf       host11     FCP        1.2t    cDOT
hana                          /vol/SS3_log_mnt00002/SS3_log_mnt00002   /dev/sdae       host11     FCP        512.0g  cDOT
hana                          /vol/SS3_data_mnt00001/SS3_data_mnt00001 /dev/sdad       host11     FCP        1.2t    cDOT
hana                          /vol/SS3_data_mnt00002/SS3_data_mnt00002 /dev/sdac       host11     FCP        1.2t    cDOT
hana                          /vol/SS3_log_mnt00002/SS3_log_mnt00002   /dev/sdab       host11     FCP        512.0g  cDOT
hana                          /vol/SS3_data_mnt00001/SS3_data_mnt00001 /dev/sdaa       host11     FCP        1.2t    cDOT
hana                          /vol/SS3_data_mnt00002/SS3_data_mnt00002 /dev/sdz        host11     FCP        1.2t    cDOT
hana                          /vol/SS3_log_mnt00002/SS3_log_mnt00002   /dev/sdy        host11     FCP        512.0g  cDOT
hana                          /vol/SS3_data_mnt00001/SS3_data_mnt00001 /dev/sdx        host11     FCP        1.2t    cDOT
hana                          /vol/SS3_data_mnt00002/SS3_data_mnt00002 /dev/sdw        host11     FCP        1.2t    cDOT
hana                          /vol/SS3_log_mnt00001/SS3_log_mnt00001   /dev/sdv        host11     FCP        512.0g  cDOT
hana                          /vol/SS3_log_mnt00001/SS3_log_mnt00001   /dev/sdu        host11     FCP        512.0g  cDOT
hana                          /vol/SS3_log_mnt00001/SS3_log_mnt00001   /dev/sdt        host11     FCP        512.0g  cDOT
hana                          /vol/SS3_log_mnt00001/SS3_log_mnt00001   /dev/sds        host11     FCP        512.0g  cDOT
hana                          /vol/SS3_log_mnt00002/SS3_log_mnt00002   /dev/sdr        host10     FCP        512.0g  cDOT
hana                          /vol/SS3_data_mnt00001/SS3_data_mnt00001 /dev/sdq        host10     FCP        1.2t    cDOT
hana                          /vol/SS3_data_mnt00002/SS3_data_mnt00002 /dev/sdp        host10     FCP        1.2t    cDOT
hana                          /vol/SS3_log_mnt00002/SS3_log_mnt00002   /dev/sdo        host10     FCP        512.0g  cDOT
hana                          /vol/SS3_data_mnt00001/SS3_data_mnt00001 /dev/sdn        host10     FCP        1.2t    cDOT
hana                          /vol/SS3_data_mnt00002/SS3_data_mnt00002 /dev/sdm        host10     FCP        1.2t    cDOT
hana                          /vol/SS3_log_mnt00002/SS3_log_mnt00002   /dev/sdl        host10     FCP        512.0g  cDOT
hana                          /vol/SS3_data_mnt00001/SS3_data_mnt00001 /dev/sdk        host10     FCP        1.2t    cDOT
hana                          /vol/SS3_data_mnt00002/SS3_data_mnt00002 /dev/sdj        host10     FCP        1.2t    cDOT
hana                          /vol/SS3_log_mnt00002/SS3_log_mnt00002   /dev/sdi        host10     FCP        512.0g  cDOT
hana                          /vol/SS3_data_mnt00001/SS3_data_mnt00001 /dev/sdh        host10     FCP        1.2t    cDOT
hana                          /vol/SS3_data_mnt00002/SS3_data_mnt00002 /dev/sdg        host10     FCP        1.2t    cDOT
hana                          /vol/SS3_log_mnt00001/SS3_log_mnt00001   /dev/sdf        host10     FCP        512.0g  cDOT
hana                          /vol/SS3_log_mnt00001/SS3_log_mnt00001   /dev/sde        host10     FCP        512.0g  cDOT
hana                          /vol/SS3_log_mnt00001/SS3_log_mnt00001   /dev/sdd        host10     FCP        512.0g  cDOT
hana                          /vol/SS3_log_mnt00001/SS3_log_mnt00001   /dev/sdc        host10     FCP        512.0g  cDOT
....
. Execute o `multipath -r` comando para obter os identificadores mundiais (WWIDs) para os nomes de arquivos do dispositivo:
+

NOTE: Neste exemplo, existem quatro LUNs.

+
....
stlrx300s8-6:~ # multipath -r
create: 3600a098038304436375d4d442d753878 undef NETAPP,LUN C-Mode
size=512G features='3 pg_init_retries 50 queue_if_no_path' hwhandler='0' wp=undef
|-+- policy='service-time 0' prio=50 status=undef
| |- 10:0:1:0 sdd  8:48   undef ready running
| |- 10:0:3:0 sdf  8:80   undef ready running
| |- 11:0:0:0 sds  65:32  undef ready running
| `- 11:0:2:0 sdu  65:64  undef ready running
`-+- policy='service-time 0' prio=10 status=undef
  |- 10:0:0:0 sdc  8:32   undef ready running
  |- 10:0:2:0 sde  8:64   undef ready running
  |- 11:0:1:0 sdt  65:48  undef ready running
  `- 11:0:3:0 sdv  65:80  undef ready running
create: 3600a098038304436375d4d442d753879 undef NETAPP,LUN C-Mode
size=1.2T features='3 pg_init_retries 50 queue_if_no_path' hwhandler='0' wp=undef
|-+- policy='service-time 0' prio=50 status=undef
| |- 10:0:1:1 sdj  8:144  undef ready running
| |- 10:0:3:1 sdp  8:240  undef ready running
| |- 11:0:0:1 sdw  65:96  undef ready running
| `- 11:0:2:1 sdac 65:192 undef ready running
`-+- policy='service-time 0' prio=10 status=undef
  |- 10:0:0:1 sdg  8:96   undef ready running
  |- 10:0:2:1 sdm  8:192  undef ready running
  |- 11:0:1:1 sdz  65:144 undef ready running
  `- 11:0:3:1 sdaf 65:240 undef ready running
create: 3600a098038304436392b4d442d6f534f undef NETAPP,LUN C-Mode
size=1.2T features='3 pg_init_retries 50 queue_if_no_path' hwhandler='0' wp=undef
|-+- policy='service-time 0' prio=50 status=undef
| |- 10:0:0:2 sdh  8:112  undef ready running
| |- 10:0:2:2 sdn  8:208  undef ready running
| |- 11:0:1:2 sdaa 65:160 undef ready running
| `- 11:0:3:2 sdag 66:0   undef ready running
`-+- policy='service-time 0' prio=10 status=undef
  |- 10:0:1:2 sdk  8:160  undef ready running
  |- 10:0:3:2 sdq  65:0   undef ready running
  |- 11:0:0:2 sdx  65:112 undef ready running
  `- 11:0:2:2 sdad 65:208 undef ready running
create: 3600a098038304436392b4d442d6f5350 undef NETAPP,LUN C-Mode
size=512G features='3 pg_init_retries 50 queue_if_no_path' hwhandler='0' wp=undef
|-+- policy='service-time 0' prio=50 status=undef
| |- 10:0:0:3 sdi  8:128  undef ready running
| |- 10:0:2:3 sdo  8:224  undef ready running
| |- 11:0:1:3 sdab 65:176 undef ready running
| `- 11:0:3:3 sdah 66:16  undef ready running
`-+- policy='service-time 0' prio=10 status=undef
  |- 10:0:1:3 sdl  8:176  undef ready running
  |- 10:0:3:3 sdr  65:16  undef ready running
  |- 11:0:0:3 sdy  65:128 undef ready running
  `- 11:0:2:3 sdae 65:224 undef ready running
....
. Edite o `/etc/multipath.conf` arquivo e adicione os WWIDs e nomes de alias.
+

NOTE: A saída de exemplo mostra o conteúdo do `/etc/multipath.conf` arquivo, que inclui nomes de alias para os quatro LUNs de um sistema de vários hosts 2-1. Se não houver `multipath.conf` nenhum arquivo disponível, você poderá criar um executando o seguinte comando: `multipath -T > /etc/multipath.conf`.

+
....
stlrx300s8-6:/ # cat /etc/multipath.conf
multipaths {
        multipath {
                wwid    3600a098038304436392b4d442d6f534f
                alias   hana-SS3_data_mnt00001
        }
        multipath {
                wwid    3600a098038304436375d4d442d753879
                alias   hana-SS3_data_mnt00002
        }
        multipath {
                wwid    3600a098038304436375d4d442d753878
                alias   hana-SS3_log_mnt00001
        }
        multipath {
                wwid    3600a098038304436392b4d442d6f5350
                alias   hana-SS3_log_mnt00002
        }
}
....
. Execute o `multipath -r` comando para recarregar o mapa de dispositivos.
. Verifique a configuração executando o `multipath -ll` comando para listar todos os LUNs, nomes de alias e caminhos ativos e de espera.
+

NOTE: A saída de exemplo a seguir mostra a saída de um 2 sistema HANA de vários hosts de mais de 1 U com dois dados e dois LUNs de log.

+
....
stlrx300s8-6:~ # multipath -ll
hana- SS3_data_mnt00002 (3600a098038304436375d4d442d753879) dm-1 NETAPP,LUN C-Mode
size=1.2T features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handler' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=enabled
| |- 10:0:1:1 sdj  8:144  active ready running
| |- 10:0:3:1 sdp  8:240  active ready running
| |- 11:0:0:1 sdw  65:96  active ready running
| `- 11:0:2:1 sdac 65:192 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 10:0:0:1 sdg  8:96   active ready running
  |- 10:0:2:1 sdm  8:192  active ready running
  |- 11:0:1:1 sdz  65:144 active ready running
  `- 11:0:3:1 sdaf 65:240 active ready running
hana- SS3_data_mnt00001 (3600a098038304436392b4d442d6f534f) dm-2 NETAPP,LUN C-Mode
size=1.2T features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handler' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=enabled
| |- 10:0:0:2 sdh  8:112  active ready running
| |- 10:0:2:2 sdn  8:208  active ready running
| |- 11:0:1:2 sdaa 65:160 active ready running
| `- 11:0:3:2 sdag 66:0   active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 10:0:1:2 sdk  8:160  active ready running
  |- 10:0:3:2 sdq  65:0   active ready running
  |- 11:0:0:2 sdx  65:112 active ready running
  `- 11:0:2:2 sdad 65:208 active ready running
hana- SS3_log_mnt00002 (3600a098038304436392b4d442d6f5350) dm-3 NETAPP,LUN C-Mode
size=512G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handler' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=enabled
| |- 10:0:0:3 sdi  8:128  active ready running
| |- 10:0:2:3 sdo  8:224  active ready running
| |- 11:0:1:3 sdab 65:176 active ready running
| `- 11:0:3:3 sdah 66:16  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 10:0:1:3 sdl  8:176  active ready running
  |- 10:0:3:3 sdr  65:16  active ready running
  |- 11:0:0:3 sdy  65:128 active ready running
  `- 11:0:2:3 sdae 65:224 active ready running
hana- SS3_log_mnt00001 (3600a098038304436375d4d442d753878) dm-0 NETAPP,LUN C-Mode
size=512G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handler' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=enabled
| |- 10:0:1:0 sdd  8:48   active ready running
| |- 10:0:3:0 sdf  8:80   active ready running
| |- 11:0:0:0 sds  65:32  active ready running
| `- 11:0:2:0 sdu  65:64  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 10:0:0:0 sdc  8:32   active ready running
  |- 10:0:2:0 sde  8:64   active ready running
  |- 11:0:1:0 sdt  65:48  active ready running
  `- 11:0:3:0 sdv  65:80  active ready running
....




== Crie grupos de volumes LVM e volumes lógicos

Esta etapa só é necessária se o LVM for usado. O exemplo a seguir é para uma configuração de host 2-1 usando SID FC5.


NOTE: Para uma configuração baseada em LVM, a configuração multipath descrita na seção anterior também deve ser concluída. Neste exemplo, oito LUNs devem ser configurados para multipathing.

. Inicialize todos os LUNs como um volume físico.
+
....
pvcreate /dev/mapper/hana-FC5_data_mnt00001
pvcreate /dev/mapper/hana-FC5_data2_mnt00001pvcreate /dev/mapper/hana-FC5_data_mnt00002
pvcreate /dev/mapper/hana-FC5_data2_mnt00002
pvcreate /dev/mapper/hana-FC5_log_mnt00001
pvcreate /dev/mapper/hana-FC5_log2_mnt00001pvcreate /dev/mapper/hana-FC5_log_mnt00002
pvcreate /dev/mapper/hana-FC5_log2_mnt00002
....
. Crie os grupos de volume para cada partição de dados e log.
+
....
vgcreate FC5_data_mnt00001 /dev/mapper/hana-FC5_data_mnt00001 /dev/mapper/hana-FC5_data2_mnt00001
vgcreate FC5_data_mnt00002 /dev/mapper/hana-FC5_data_mnt00002 /dev/mapper/hana-FC5_data2_mnt00002
vgcreate FC5_log_mnt00001 /dev/mapper/hana-FC5_log_mnt00001 /dev/mapper/hana-FC5_log2_mnt00001
vgcreate FC5_log_mnt00002 /dev/mapper/hana-FC5_log_mnt00002 /dev/mapper/hana-FC5_log2_mnt00002
....
. Crie um volume lógico para cada partição de dados e log. Use um tamanho de faixa que seja igual ao número de LUNs usados por grupo de volume (no exemplo dois) e um tamanho de faixa de 256K para dados e 64k para log. O SAP suporta apenas um volume lógico por grupo de volumes.
+
....
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00001
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00002
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00002
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00001
....
. Examine os volumes físicos, os grupos de volume e os grupos de vol em todos os outros hosts.
+
....
modprobe dm_mod
pvscan
vgscan
lvscan
....
+

NOTE: Se os comandos acima não encontrarem os volumes, é necessário reiniciar.

. Para montar os volumes lógicos, os volumes lógicos devem ser ativados. Para ativar os volumes, execute o seguinte comando:
+
....
vgchange -a y 
....




== Criar sistemas de arquivos

Para criar o sistema de arquivos XFS em cada LUN pertencente ao sistema HANA, execute uma das seguintes ações:

* Para um sistema de host único, crie o sistema de arquivos XFS nos dados, log e `/hana/shared` LUNs.


....
stlrx300s8-6:/ # mkfs.xfs /dev/mapper/hana-SS3_data_mnt00001
stlrx300s8-6:/ # mkfs.xfs /dev/mapper/hana-SS3_log_mnt00001
stlrx300s8-6:/ # mkfs.xfs /dev/mapper/hana-SS3_shared
....
* Para um sistema de vários hosts, crie o sistema de arquivos XFS em todos os dados e LUNs de log.


....
stlrx300s8-6:~ # mkfs.xfs /dev/mapper/hana-SS3_log_mnt00001
stlrx300s8-6:~ # mkfs.xfs /dev/mapper/hana-SS3_log_mnt00002
stlrx300s8-6:~ # mkfs.xfs /dev/mapper/hana-SS3_data_mnt00001
stlrx300s8-6:~ # mkfs.xfs /dev/mapper/hana-SS3_data_mnt00002
....
* Se o LVM for usado, crie o sistema de arquivos XFS em todos os dados e Registre volumes lógicos.


....
mkfs.xfs FC5_data_mnt00001-vol
mkfs.xfs FC5_data_mnt00002-vol
mkfs.xfs FC5_log_mnt00001-vol
mkfs.xfs FC5_log_mnt00002-vol
....

NOTE: Os comandos de exemplo de vários hosts mostram um sistema HANA de mais de 2 a 1 host múltiplo.



== Crie pontos de montagem

Para criar os diretórios de ponto de montagem necessários, execute uma das seguintes ações:

* Para um sistema de host único, defina permissões e crie pontos de montagem no host do banco de dados.


....
stlrx300s8-6:/ # mkdir -p /hana/data/SS3/mnt00001
stlrx300s8-6:/ # mkdir -p /hana/log/SS3/mnt00001
stlrx300s8-6:/ # mkdir -p /hana/shared

stlrx300s8-6:/ # chmod –R 777 /hana/log/SS3
stlrx300s8-6:/ # chmod –R 777 /hana/data/SS3
stlrx300s8-6:/ # chmod 777 /hana/shared
....
* Para um sistema de vários hosts, defina permissões e crie pontos de montagem em todos os hosts de trabalho e de espera.



NOTE: Os comandos de exemplo mostram um sistema HANA de vários hosts de 2 a 1.

....
stlrx300s8-6:/ # mkdir -p /hana/data/SS3/mnt00001
stlrx300s8-6:/ # mkdir -p /hana/log/SS3/mnt00001
stlrx300s8-6:/ # mkdir -p /hana/data/SS3/mnt00002
stlrx300s8-6:/ # mkdir -p /hana/log/SS3/mnt00002
stlrx300s8-6:/ # mkdir -p /hana/shared

stlrx300s8-6:/ # chmod –R 777 /hana/log/SS3
stlrx300s8-6:/ # chmod –R 777 /hana/data/SS3
stlrx300s8-6:/ # chmod 777 /hana/shared
....

NOTE: As mesmas etapas devem ser executadas para uma configuração de sistema com Linux LVM.



== Montar sistemas de arquivos

Para montar sistemas de arquivos durante a inicialização do sistema usando o `/etc/fstab` arquivo de configuração, execute as seguintes etapas:

. Execute uma das seguintes ações:
+
** Para um sistema de host único, adicione os sistemas de arquivos necessários ao `/etc/fstab` arquivo de configuração.
+

NOTE: Os sistemas de arquivos XFS para o LUN de dados e log devem ser montados com as `relatime` opções de montagem e. `inode64`

+
....
stlrx300s8-6:/ # cat /etc/fstab
/dev/mapper/hana-SS3_shared /hana/shared xfs defaults 0 0
/dev/mapper/hana-SS3_log_mnt00001 /hana/log/SS3/mnt00001 xfs relatime,inode64 0 0
/dev/mapper/hana-SS3_data_mnt00001 /hana/data/SS3/mnt00001 xfs relatime,inode64 0 0
....
+
Se o LVM for usado, use os nomes de volume lógico para dados e log.

+
....
# cat /etc/fstab
/dev/mapper/hana-FC5_shared /hana/shared xfs defaults 0 0
/dev/mapper/FC5_log_mnt00001-vol /hana/log/FC5/mnt00001 xfs relatime,inode64 0 0
/dev/mapper/FC5_data_mnt00001-vol /hana/data/FC5/mnt00001 xfs relatime,inode64 0 0
....
** Para um sistema de vários hosts, adicione o `/hana/shared` sistema de arquivos ao `/etc/fstab` arquivo de configuração de cada host.
+

NOTE: Todos os sistemas de arquivos de log e dados são montados pelo conector de storage SAP HANA.

+
....
stlrx300s8-6:/ # cat /etc/fstab
<storage-ip>:/hana_shared /hana/shared nfs rw,vers=3,hard,timeo=600,intr,noatime,nolock 0 0
....


. Para montar os sistemas de arquivos, execute o `mount –a` comando em cada host.

