---
sidebar: sidebar 
permalink: bp/kvm-hana-introduction.html 
keywords: introduction,KVM, SAP HANA, tailored data center integration, FCP, NFS 
summary: Este guia fornece informações sobre como configurar o SUSE KVM para SAP HANA usando o armazenamento NetApp . 
---
= SAP HANA com SUSE KVM e armazenamento NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este guia fornece informações sobre como configurar o SUSE KVM para SAP HANA usando o armazenamento NetApp .

Marco Schoen, NetApp



== Introdução

Este documento descreve os passos adicionais necessários para a implementação do SAP HANA Single-Host em SUSE KVM utilizando armazenamento NetApp .  É baseado em https://documentation.suse.com/sbp/sap-15/pdf/SBP-SLES4SAP-HANAonKVM-SLES15SP5_en.pdf["Melhores práticas da SUSE para SAP HANA em KVM"] .

Este guia mostra principalmente como configurar interfaces de rede para SR-IOV (Virtualização de E/S de Raiz Única) no host KVM, atribuir essas interfaces virtuais (VF) a uma máquina virtual (VM) e configurar as interfaces dentro da VM para acessar o armazenamento do SAP HANA usando NFS.  Além disso, descreve como configurar o FCP para uso com o SAP HANA dentro da VM.


NOTE: O protocolo SR-IOV deve ser utilizado para comunicação de rede SAP HANA e para acesso ao armazenamento usando NFS.  As portas HBA FCP físicas devem ser atribuídas à VM como dispositivos PCI para usar LUNs FCP.  Sistemas SAP HANA com múltiplos hosts não são suportados.



== Pré-requisitos

Este guia é válido para o Linux Enterprise Server para SAP Applications 15 SP5/SP6 como host KVM.  É necessário utilizar servidores SAP HANA certificados e armazenamento NetApp .  Consulte o Diretório de Hardware do SAP HANA para obter opções disponíveis. https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN[]

A configuração e a instalação dos hosts KVM e da máquina virtual devem ser feitas de acordo com o seguinte: https://documentation.suse.com/sbp/sap-15/pdf/SBP-SLES4SAP-HANAonKVM-SLES15SP5_en.pdf["Melhores práticas da SUSE para SAP HANA em KVM"] .

Para obter as informações mais recentes, incluindo a arquitetura de CPU compatível e as limitações, consulte a Nota SAP +https://me.sap.com/notes/3538596["3538596 - SAP HANA em virtualização SUSE KVM com SLES 15 SP5 - SAP para mim"]
