---
sidebar: sidebar 
permalink: bp/sap-oracle-snapman_pdf_link.html 
keywords: tr-4250, pdf, sap, hana, oracle, unix, nfs, dr, snap creator 
summary: Este documento aborda os desafios de projetar soluções de storage para dar suporte a produtos de suíte de negócios SAP usando um banco de dados Oracle. O foco principal deste documento são os desafios comuns de design, implantação, operação e gerenciamento da infraestrutura de storage enfrentados por líderes de negócios e TI que usam a última geração de soluções SAP. As recomendações neste documento são genéricas; elas não são específicas para um aplicativo SAP ou para o tamanho e escopo da implementação SAP. 
---
= TR-4250: SAP com Oracle em UNIX e NFS com NetApp ONTAP e SnapManager para SAP 3,4HANA
:allow-uri-read: 
:firstname: : hardbreaks:
:author: : hardbreaks:
:authorinitials: :
:authors: : hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este documento aborda os desafios de projetar soluções de storage para dar suporte a produtos de suíte de negócios SAP usando um banco de dados Oracle. O foco principal deste documento são os desafios comuns de design, implantação, operação e gerenciamento da infraestrutura de storage enfrentados por líderes de negócios e TI que usam a última geração de soluções SAP. As recomendações neste documento são genéricas; elas não são específicas para um aplicativo SAP ou para o tamanho e escopo da implementação SAP. Este documento pressupõe que o leitor tenha uma compreensão básica da tecnologia e operação dos produtos NetApp e SAP. O documento foi desenvolvido com base na interação da equipe técnica da NetApp, SAP, Oracle e nossos clientes.

Nils Bauer, NetApp

link:https://www.netapp.com/pdf.html?item=/media/19525-tr-4250.pdf["https://www.netapp.com/pdf.html?item=/media/19525-tr-4250.pdf"]
