---
sidebar: sidebar 
permalink: bp/saphana-fas-nfs_i_o_stack_configuration_for_sap_hana.html 
keywords: io, stack, configuration, sap, hana, fas, nfs 
summary: A partir do SAP HANA 1,0 SPS10, a SAP introduziu parâmetros para ajustar o comportamento de e/S e otimizar o banco de dados para os sistemas de arquivos e storage usados. 
---
= Configuração de stack de e/S para SAP HANA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partir do SAP HANA 1,0 SPS10, a SAP introduziu parâmetros para ajustar o comportamento de e/S e otimizar o banco de dados para os sistemas de arquivos e storage usados.

A NetApp realizou testes de desempenho para definir os valores ideais. A tabela a seguir lista os valores ideais inferidos dos testes de desempenho.

|===
| Parâmetro | Valor 


| max_parallel_io_requests | 128 


| async_read_submit | ligado 


| async_write_submit_active | ligado 


| async_write_submit_blocks | tudo 
|===
Para versões do SAP HANA 1,0 até SPS12HANA, esses parâmetros podem ser definidos durante a instalação do banco de dados SAP HANA, conforme descrito na nota SAP https://launchpad.support.sap.com/["2267798: Configuração do banco de dados SAP HANA durante a instalação usando hdbparam"^] .

Como alternativa, os parâmetros podem ser definidos após a instalação do banco de dados SAP HANA usando a `hdbparam` estrutura.

....
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.max_parallel_io_requests=128
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_write_submit_active=on
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_read_submit=on
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_write_submit_blocks=all
....
A partir do SAP HANA 2,0, `hdbparam` foi obsoleto e os parâmetros foram movidos para `global.ini`o . Os parâmetros podem ser definidos usando comandos SQL ou SAP HANA Studio. Para obter mais detalhes, consulte a nota SAP https://launchpad.support.sap.com/["2399079: Eliminação do hdbparam em HANA 2"^] . Você também pode definir os parâmetros dentro de global.ini como mostrado no seguinte texto:

....
nf2adm@stlrx300s8-6: /usr/sap/NF2/SYS/global/hdb/custom/config> cat global.ini
…
[fileio]
async_read_submit = on
async_write_submit_active = on
max_parallel_io_requests = 128
async_write_submit_blocks = all
…
....
Desde o SAP HANA 2,0 SPS5, o `setParameter.py` script pode ser usado para definir os parâmetros corretos:

....
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00/exe/python_support>
python setParameter.py -set=SYSTEM/global.ini/fileio/max_parallel_io_requests=128
python setParameter.py -set=SYSTEM/global.ini/fileio/async_read_submit=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_active=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_blocks=all
....