---
sidebar: sidebar 
permalink: lifecycle/sc-copy-clone-supported-infrastructure.html 
keywords: tr4667, 4667, SAP HANA, cloning, system refresh 
summary: As soluções da NetApp para otimizar o gerenciamento do ciclo de vida do SAP são integradas ao banco de dados SAP HANA e às ferramentas de gerenciamento de ciclo de vida, combinando proteção de dados eficiente integrada a aplicações com o provisionamento flexível dos sistemas de teste do SAP. 
---
= Infraestrutura e cenários compatíveis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este documento aborda os cenários de clonagem e atualização do sistema SAP para sistemas SAP HANA executados em sistemas NetApp no local, no Amazon FSX para sistemas NetApp ONTAP e no Azure NetApp Files. No entanto, nem todos os recursos e cenários estão disponíveis em todas as plataformas de storage. A tabela abaixo resume as configurações suportadas.

No documento, estamos usando um cenário de SAP HANA executado em sistemas NetApp locais com NFS como protocolo de storage. A maioria das etapas do fluxo de trabalho são idênticas nas diferentes plataformas e, se houver diferenças, elas são destacadas neste documento.

[cols="25%,25%,25%,25%"]
|===
|  | *Sistemas NetApp locais* | *AWS FSX for NetApp ONTAP* | *Azure NetApp Files* 


| Protocolo de armazenamento e sistema de arquivos | Bare metal: NFS, FC com XFS VMware: NFS em montagens no convidado, FC com VMDKs e XFS | NFS | NFS 


| Clone fino (FlexClone) | Sim | Sim | Sim, mas não integrado ao SnapCenter 


| Operação de divisão de clones | Sim | Sim | Sim, mas não integrado ao SnapCenter 


| Clonagem do primário | Sim | Sim | Sim 


| Clonagem a partir de backup externo | Sim | Sim | Sim, restaurar para um novo volume a partir de backup 


| Clonagem no local de DR | Sim | Sim | Sim, mas não integrado ao SnapCenter 
|===
Informações adicionais sobre operações de atualização do sistema SAP para HANA com VMware VMFS e sistemas NetApp ASAr2 podem ser encontradas em  https://docs.netapp.com/us-en/netapp-solutions-sap/backup/hana-sc-vmfs-asar2sap-refresh.html["Atualização do sistema SAP"].
